name: Metrics

on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics plugin
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Display metrics
          plugin_languages: yes
          plugin_languages_ignored: "c#, jupyter notebook, matlab, racket"
          plugin_lines: yes

      - name: Stars, LeetCode plugins
        uses: lowlighter/metrics@master
        with:
          filename: github-metrics-plugins.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          # Display latest starred repositories
          plugin_stars: yes
          plugin_stars_limit: 3
          # Displays statistics from LeetCode
          plugin_leetcode: yes
          plugin_leetcode_user: rajatdiptabiswas
          plugin_leetcode_sections: solved, skills
